name: Scheduled Job

on:
  schedule:
    - cron: "0 5 * * *"   # everyday at 5:00 AM UTC or IST (UTC+5:30) = 10:30 PM IST
  workflow_dispatch:        # allows manual run button

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install deps
        run: pip install requests python-dotenv

      - name: Run script
        env:
          NAUKRI_COOKIES: ${{ secrets.NAUKRI_COOKIES }}
          NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
          GOOGLE_DRIVE_FILE_ID: ${{ secrets.GOOGLE_DRIVE_FILE_ID }}
          NAUKRI_FORM_KEY: ${{ secrets.NAUKRI_FORM_KEY }}
          RESUME_FILENAME: ${{ secrets.RESUME_FILENAME }}
        run: python updateDaily.py